ALTER TABLE vendors ADD COLUMN IF NOT EXISTS gst_number VARCHAR(40);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS bank_name VARCHAR(120);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS bank_account_masked VARCHAR(40);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS compliance_status VARCHAR(30) DEFAULT 'PENDING';
CREATE TABLE IF NOT EXISTS purchase_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), po_number VARCHAR(40) UNIQUE NOT NULL, vendor_id UUID NOT NULL REFERENCES vendors(id), project_id UUID REFERENCES projects(id), po_date DATE NOT NULL, material_service VARCHAR(300) NOT NULL, quantity NUMERIC(12,2) NOT NULL DEFAULT 1, rate NUMERIC(15,2) NOT NULL, gst_amount NUMERIC(15,2) NOT NULL DEFAULT 0, total_amount NUMERIC(15,2) NOT NULL, terms TEXT, approval_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', delivery_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', created_by UUID REFERENCES users(id), approved_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS po_id UUID REFERENCES purchase_orders(id);
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS invoice_file VARCHAR(240);
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS payment_date DATE;
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(30);
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS transaction_reference VARCHAR(120);
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES users(id);
ALTER TABLE petty_cash_entries ADD COLUMN IF NOT EXISTS receipt_file VARCHAR(240);
ALTER TABLE petty_cash_entries ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE petty_cash_entries ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMPTZ;
ALTER TABLE petty_cash_entries ADD COLUMN IF NOT EXISTS reversal_reason VARCHAR(500);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_vendor_status ON purchase_orders(vendor_id,approval_status);
CREATE INDEX IF NOT EXISTS idx_vendor_bills_due_status ON vendor_bills(due_date,status);
