package com.saivandan.crm.lead;
public enum LeadStatus { NEW, CONTACTED, QUALIFIED, NOT_INTERESTED, FUTURE_PROSPECT, WRONG_NUMBER, DUPLICATE, SITE_VISIT_SCHEDULED, VISITED, NEGOTIATION, BOOKING_PENDING, BOOKED, LOST }

