import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Bell, BellRing, Building2, CalendarClock, ChevronDown, ClipboardList, LayoutDashboard, LogOut, Menu, Plus, Search, Users, X, Settings, ShieldCheck, UserRound, BriefcaseBusiness, FileText, Wrench, Headphones, WalletCards, Truck, ClipboardCheck, Download, Printer, CheckCheck } from 'lucide-react';
import { api, Dashboard as DashboardData, Lead, User, Workspace, WorkspaceRecord } from './api';

const nav = [
  { icon: LayoutDashboard, name: 'Overview' }, { icon: Users, name: 'Leads' }, { icon: UserRound, name: 'User Management' }, { icon: Building2, name: 'Project Management' }, { icon: Users, name: 'Lead Management' }, { icon: UserRound, name: 'Employee Management' }, { icon: Truck, name: 'Vendor Management' }, { icon: WalletCards, name: 'Finance' }, { icon: BriefcaseBusiness, name: 'Payroll' }, { icon: ClipboardList, name: 'Reports' }, { icon: Settings, name: 'System Configuration' }, { icon: ShieldCheck, name: 'Audit Logs' },
  { icon: Users, name: 'Sales Monitoring' }, { icon: FileText, name: 'Negotiation' }, { icon: ClipboardList, name: 'Lead Qualification' }, { icon: CalendarClock, name: 'Follow-ups' }, { icon: Building2, name: 'Properties' }, { icon: CalendarClock, name: 'Site Visits' }, { icon: FileText, name: 'Bookings' }, { icon: FileText, name: 'Documents' }, { icon: Users, name: 'Customers' }, { icon: UserRound, name: 'Employees' }, { icon: CalendarClock, name: 'Attendance' }, { icon: ClipboardCheck, name: 'Leave' }, { icon: BriefcaseBusiness, name: 'Salary' }, { icon: WalletCards, name: 'Customer Payments' }, { icon: FileText, name: 'Loans' }, { icon: FileText, name: 'Agreements' }, { icon: WalletCards, name: 'Vendor Payments' }, { icon: WalletCards, name: 'Petty Cash' }, { icon: Truck, name: 'Vendors' }, { icon: ClipboardList, name: 'Purchase Orders' }, { icon: FileText, name: 'Vendor Bills' }, { icon: ClipboardList, name: 'Vendor Ledger' }, { icon: Headphones, name: 'Complaints' }, { icon: Wrench, name: 'Maintenance' }, { icon: ClipboardCheck, name: 'Possession' }
];
const navFor = (roles: string[]) => {
  const has = (role: string) => roles.includes(role);
  const names = has('SUPER_ADMIN') ? ['Overview','User Management','Project Management','Lead Management','Employee Management','Vendor Management','Finance','Payroll','Reports','System Configuration','Audit Logs'] : has('SALES_MANAGER') ? ['Overview','Lead Management','Sales Monitoring','Negotiation','Reports'] : has('SALES_EXECUTIVE') ? ['Overview','Leads','Lead Qualification','Follow-ups','Properties','Site Visits','Negotiation','Bookings','Documents','Customers'] : has('HR') ? ['Overview','Employees','Attendance','Leave','Payroll','Salary','Reports'] : has('FINANCE') ? ['Overview','Customer Payments','Loans','Agreements','Vendor Payments','Petty Cash','Reports'] : has('VENDOR') ? ['Overview','Vendors','Purchase Orders','Vendor Bills','Vendor Ledger'] : ['Overview','Complaints','Maintenance','Customers','Possession'];
  return nav.filter(item => names.includes(item.name));
};
const canCreateLead = (roles: string[]) => roles.some(role => ['SUPER_ADMIN', 'SALES_MANAGER', 'SALES_EXECUTIVE'].includes(role));
const demoAccounts = [
  ['Super Admin', 'admin@saivandan.local'], ['Sales Manager', 'sales.manager@saivandan.local'], ['Sales Executive', 'sales.executive@saivandan.local'],
  ['HR & Payroll', 'hr@saivandan.local'], ['Accounts & Finance', 'finance@saivandan.local'], ['Vendor Manager', 'vendor@saivandan.local'], ['Customer Support', 'support@saivandan.local']
] as const;

type NotificationItem = { id: string; title: string; detail: string; tone: 'gold' | 'green' | 'coral'; read: boolean };
const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
function downloadCsv(filename: string, rows: Record<string, unknown>[]) {
  if (!rows.length) return;
  const columns = Array.from(new Set(rows.flatMap(row => Object.keys(row))));
  const csv = [columns.map(csvCell).join(','), ...rows.map(row => columns.map(column => csvCell(row[column])).join(','))].join('\n');
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
}

export function App() {
  const [user, setUser] = useState<User | null>(null); const [active, setActive] = useState('Overview'); const [leads, setLeads] = useState<Lead[]>([]); const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [drawer, setDrawer] = useState(false); const [newLead, setNewLead] = useState(false); const [notificationOpen, setNotificationOpen] = useState(false); const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  useEffect(() => { if (localStorage.getItem('sv_access_token')) api.me().then(setUser).catch(() => localStorage.clear()); }, []);
  useEffect(() => { if (user) { api.leads().then(p => setLeads(p.content)).catch(() => setLeads([])); api.dashboard().then(data => { setDashboard(data); setNotifications(data.queue.map((item, index) => ({ id: `${data.role}-${index}`, title: item.label, detail: `${item.count} ${item.note.toLowerCase()}`, tone: index % 3 === 0 ? 'gold' : index % 3 === 1 ? 'green' : 'coral', read: false }))); }).catch(() => setDashboard(null)); } }, [user]);
  const stats = useMemo(() => ({ leads: leads.length, qualified: leads.filter(l => ['QUALIFIED', 'SITE_VISIT_SCHEDULED', 'VISITED', 'NEGOTIATION'].includes(l.status)).length, visits: leads.filter(l => l.status === 'SITE_VISIT_SCHEDULED').length, hot: leads.filter(l => l.temperature === 'HOT').length }), [leads]);
  if (!user) return <Login onLoggedIn={setUser}/>;
  const visibleNav = navFor(user.roles); const canCreate = canCreateLead(user.roles); const roleLabel = user.roles[0]?.replaceAll('_', ' ') ?? 'USER';
  return <div className="shell">
    <aside className={drawer ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">SV</div><div><strong>Sai Vandan</strong><span>REAL ESTATE CRM</span></div><button className="mobile-close" onClick={() => setDrawer(false)}><X size={20}/></button></div><div className="project-chip"><span>{roleLabel}</span><strong>Sai Vandan Complex</strong><ChevronDown size={15}/></div><nav>{visibleNav.map(item => <button className={active === item.name ? 'nav-item active' : 'nav-item'} onClick={() => { setActive(item.name); setDrawer(false); }} key={item.name}><item.icon size={19}/>{item.name}</button>)}</nav><div className="sidebar-bottom"><div className="support">Need assistance?<br/><b>Contact system support</b></div><button className="nav-item" onClick={() => { localStorage.clear(); setUser(null); }}><LogOut size={19}/>Sign out</button></div></aside>
    {drawer && <div className="overlay" onClick={() => setDrawer(false)}/>}
    <main><header><button className="icon-button hamburger" onClick={() => setDrawer(true)}><Menu size={22}/></button><div className="header-title"><p>Friday, 31 July 2026</p><h1>{active === 'Overview' ? `Good morning, ${user.fullName.split(' ')[0]}` : active}</h1></div><div className="header-actions"><label className="search"><Search size={18}/><input placeholder="Search customers, units..."/></label><div className="notification-wrap"><button className="icon-button notification" aria-label="Notifications" onClick={() => setNotificationOpen(open => !open)}><Bell size={19}/>{notifications.some(item => !item.read) && <i/>}</button>{notificationOpen && <div className="notification-panel"><div className="notification-head"><div><p className="eyebrow">NOTIFICATION CENTRE</p><h3>Priority updates</h3></div><button className="text-button" onClick={() => setNotifications(items => items.map(item => ({ ...item, read: true })))}><CheckCheck size={14}/> Mark read</button></div>{notifications.length ? notifications.map(item => <button className={`notification-row ${item.read ? 'read' : ''}`} key={item.id} onClick={() => setNotifications(items => items.map(current => current.id === item.id ? { ...current, read: true } : current))}><span className={`notification-dot ${item.tone}`}><BellRing size={13}/></span><span><b>{item.title}</b><small>{item.detail}</small></span></button>) : <p className="notification-empty">You are all caught up.</p>}</div>}</div><div className="avatar">{user.fullName.split(' ').map(s => s[0]).slice(0, 2).join('')}</div></div></header>
    {active === 'Overview' ? <Dashboard dashboard={dashboard} leads={leads} canCreate={canCreate} onLead={() => setNewLead(true)}/> : active === 'Leads' ? <Leads leads={leads} canCreate={canCreate} onLead={() => setNewLead(true)}/> : <WorkspaceView module={active} />} </main>
    {newLead && canCreate && <NewLead onClose={() => setNewLead(false)} onCreated={lead => { setLeads(current => [lead, ...current]); setDashboard(null); api.dashboard().then(setDashboard); setNewLead(false); setActive('Leads'); }}/>} </div>;
}

function Login({ onLoggedIn }: { onLoggedIn: (u: User) => void }) {
  const [email, setEmail] = useState('admin@saivandan.local'); const [password, setPassword] = useState('ChangeMe!2026'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const result = await api.login(email, password); localStorage.setItem('sv_access_token', result.accessToken); localStorage.setItem('sv_refresh_token', result.refreshToken); onLoggedIn(result.user); } catch (err) { setError(err instanceof Error ? err.message : 'Could not sign in.'); } finally { setBusy(false); } };
  return <div className="login-page"><section className="login-panel"><div className="brand"><div className="brand-mark">SV</div><div><strong>Sai Vandan</strong><span>REAL ESTATE CRM</span></div></div><div className="login-copy"><p className="eyebrow">WELCOME BACK</p><h1>Built for every<br/>property moment.</h1><p>One elegant workspace for your sales, inventory, finance and customer teams.</p></div><div className="login-building"/></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><p className="eyebrow">SECURE SIGN IN</p><h2>Welcome to Sai Vandan</h2><p className="muted">Choose a workspace below. Every demo account uses the password <b>ChangeMe!2026</b>.</p>{error && <p className="error">{error}</p>}<label>Work email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required/></label><button className="primary full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in securely'}</button><div className="demo-heading"><span>DEMO WORKSPACES</span><small>Click an account to fill login</small></div><div className="demo-accounts">{demoAccounts.map(([role, accountEmail]) => <button type="button" className={email === accountEmail ? 'demo-account selected' : 'demo-account'} key={accountEmail} onClick={() => { setEmail(accountEmail); setPassword('ChangeMe!2026'); }}><span>{role}</span><small>{accountEmail}</small><b>ChangeMe!2026</b></button>)}</div></form></section></div>;
}

function Dashboard({ dashboard, leads, canCreate, onLead }: { dashboard: DashboardData | null; leads: Lead[]; canCreate: boolean; onLead: () => void }) {
  if (!dashboard) return <div className="page coming"><p className="eyebrow">LOADING YOUR WORKSPACE</p><h2>Preparing dashboard...</h2></div>;
  const tones = ['green', 'gold', 'blue', 'coral'];
  return <div className="page"><div className="page-top"><div><p className="eyebrow">{dashboard.subtitle}</p><h2>{dashboard.title}</h2></div>{canCreate && <button className="primary" onClick={onLead}><Plus size={18}/>New enquiry</button>}</div><section className="stat-grid">{dashboard.metrics.map((metric, index) => <Stat key={metric.label} label={metric.label} value={metric.value} change={metric.note} tone={tones[index % tones.length]}/>)}</section><section className="dashboard-grid"><article className="card performance"><div className="card-head"><div><p className="eyebrow">ROLE WORKSPACE</p><h3>{dashboard.role.replaceAll('_', ' ')}</h3></div><span className="count">LIVE</span></div><div className="bar-chart">{dashboard.metrics.slice(0, 8).map((metric, index) => <div key={metric.label}><span>{metric.label}</span><i style={{ height: `${38 + (index % 5) * 13}%` }}/></div>)}</div><div className="chart-legend"><span><i className="dot green"/>Role-specific data</span><strong>{dashboard.modules.length} modules enabled</strong></div></article><article className="card goals"><p className="eyebrow">YOUR ACCESS</p><h3>{dashboard.modules.length} <span>active modules</span></h3><div className="progress"><i style={{ width: `${Math.min(100, Math.max(28, dashboard.modules.length * 8))}%` }}/></div><p><b>{dashboard.queue.reduce((total, item) => total + item.count, 0)}</b> actions in your queue</p><button className="text-button">Role controls active <span>-&gt;</span></button></article><article className="card followups"><div className="card-head"><div><p className="eyebrow">ACTION QUEUE</p><h3>Priority work</h3></div><span className="count">{dashboard.queue.reduce((total, item) => total + item.count, 0)}</span></div>{dashboard.queue.map((item, index) => <div className="followup" key={item.label}><div className={`initial ${index === 1 ? 'sand' : ''}`}>{item.count}</div><div><b>{item.label}</b><span>{item.note}</span></div><button>Open</button></div>)}</article></section><section className="card feature-panel"><div className="card-head"><div><p className="eyebrow">AUTHORISED FEATURES</p><h3>What you can do</h3></div><span className="count">{dashboard.features.length}</span></div><div className="feature-chips">{dashboard.features.map(feature => <span key={feature}>{feature}</span>)}</div></section><section className="card recent"><div className="card-head"><div><p className="eyebrow">RECENT CRM ACTIVITY</p><h3>Lead pipeline</h3></div>{canCreate && <button className="text-button" onClick={onLead}>Add enquiry</button>}</div><LeadTable leads={leads.slice(0, 5)}/></section></div>;
}
function Stat({ label, value, change, tone = 'green' }: { label: string; value: string; change: string; tone?: string }) { return <article className={`stat-card ${tone}`}><p>{label}</p><h3>{value}</h3><span>{change}</span></article>; }
function Leads({ leads, canCreate, onLead }: { leads: Lead[]; canCreate: boolean; onLead: () => void }) { return <div className="page"><div className="page-top"><div><p className="eyebrow">CUSTOMER RELATIONSHIP MANAGEMENT</p><h2>Lead pipeline</h2></div>{canCreate && <button className="primary" onClick={onLead}><Plus size={18}/>New enquiry</button>}</div><section className="card recent"><div className="filters"><button className="filter active">All leads</button><button className="filter">New</button><button className="filter">Qualified</button><button className="filter">Follow-up due</button></div><LeadTable leads={leads}/></section></div>; }
function LeadTable({ leads }: { leads: Lead[] }) { return <div className="table-wrap"><table><thead><tr><th>Lead</th><th>Source</th><th>Status</th><th>Assigned to</th><th>Created</th></tr></thead><tbody>{leads.length ? leads.map(l => <tr key={l.id}><td><b>{l.customerName}</b><small>{l.mobile} - {l.leadNumber}</small></td><td>{l.source}</td><td><span className={`badge ${l.status.toLowerCase()}`}>{l.status.replaceAll('_', ' ')}</span></td><td>{l.assignedTo ?? 'Unassigned'}</td><td>{new Date(l.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</td></tr>) : <tr><td colSpan={5} className="empty">No enquiries yet. Add your first customer lead to begin.</td></tr>}</tbody></table></div>; }
function NewLead({ onClose, onCreated }: { onClose: () => void; onCreated: (l: Lead) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setBusy(true); const f = new FormData(e.currentTarget); try { const lead = await api.createLead({ customerName: f.get('customerName'), mobile: f.get('mobile'), email: f.get('email') || null, city: f.get('city') || null, source: f.get('source'), preferredConfiguration: f.get('configuration') || null, temperature: f.get('temperature'), loanRequired: f.get('loanRequired') === 'on', purchasePurpose: f.get('purchasePurpose') || null, notes: f.get('notes') || null }); onCreated(lead); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save lead.'); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW CUSTOMER</p><h2>Create enquiry</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div>{error && <p className="error">{error}</p>}<div className="form-grid"><label>Customer name<input name="customerName" required placeholder="Full name"/></label><label>Mobile number<input name="mobile" required placeholder="10-digit mobile number"/></label><label>Email<input name="email" type="email" placeholder="name@email.com"/></label><label>City<input name="city" placeholder="City"/></label><label>Lead source<select name="source" defaultValue="Website"><option>Website</option><option>Walk-in</option><option>Referral</option><option>WhatsApp</option><option>Facebook / Instagram</option><option>Google Ads</option><option>Phone Call</option><option>Property Portal</option></select></label><label>Configuration<select name="configuration"><option value="">Not decided</option><option>1 BHK</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select></label><label>Priority<select name="temperature" defaultValue="WARM"><option value="HOT">Hot</option><option value="WARM">Warm</option><option value="COLD">Cold</option></select></label><label className="check"><input type="checkbox" name="loanRequired"/> Loan assistance required</label><label className="wide">Notes<textarea name="notes" placeholder="Requirement, budget, preferred location..."/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving...' : 'Create enquiry'}</button></div></form></div>;
}
function WorkspaceView({ module }: { module: string }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [records, setRecords] = useState<WorkspaceRecord[]>([]); const [error, setError] = useState(''); const [adding, setAdding] = useState(false); const [saving, setSaving] = useState(false);
  const key = ({ Inventory: 'inventory', 'Site Visits': 'site-visits', Collections: 'collections', Reports: 'reports', 'Project Management': 'project-management', 'Lead Management': 'lead-management', 'Customer Payments': 'customer-payments', Properties: 'properties', 'Vendor Ledger': 'vendor-ledger' } as Record<string, string>)[module] ?? module.toLowerCase().replaceAll(' ', '-');
  useEffect(() => { setWorkspace(null); setRecords([]); setError(''); Promise.all([api.workspace(key), api.records(key)]).then(([data, saved]) => { setWorkspace(data); setRecords(saved); }).catch(err => setError(err instanceof Error ? err.message : 'Unable to load this workspace.')); }, [key]);
  if (error) return <div className="page coming"><p className="eyebrow">ROLE RESTRICTION</p><h2>Access unavailable</h2><p>{error}</p></div>;
  if (!workspace) return <div className="page coming"><p className="eyebrow">LOADING MODULE</p><h2>Preparing {module}...</h2></div>;
  const columns = workspace.rows.length ? Object.keys(workspace.rows[0]) : [];
  const save = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSaving(true); const form = new FormData(e.currentTarget); try { const created = await api.createRecord(key, { title: String(form.get('title') || ''), status: String(form.get('status') || 'OPEN'), details: String(form.get('details') || '') }); setRecords(current => [created, ...current]); setAdding(false); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save record.'); } finally { setSaving(false); } };
  const reportRows = [...workspace.rows, ...records.map(record => ({ title: record.title, status: record.status, details: record.details, createdAt: record.createdAt }))] as Record<string, unknown>[];
  return <div className="page"><div className="page-top"><div><p className="eyebrow">{workspace.role.replaceAll('_', ' ')} WORKSPACE</p><h2>{workspace.title}</h2></div><div className="page-actions"><button className="secondary" onClick={() => downloadCsv(`${key}-report.csv`, reportRows)}><Download size={16}/>Download CSV</button><button className="secondary" onClick={() => window.print()}><Printer size={16}/>Print</button><button className="primary" onClick={() => setAdding(true)}><Plus size={18}/>Add record</button></div></div><section className="card recent"><div className="card-head"><div><p className="eyebrow">LIVE DATA</p><h3>{workspace.rows.length + records.length} records available</h3></div><span className="count">CONNECTED</span></div><div className="table-wrap"><table><thead><tr>{columns.map(column => <th key={column}>{column.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{workspace.rows.map((row, index) => <tr key={index}>{columns.map(column => <td key={column}>{String(row[column] ?? '-').replaceAll('_', ' ')}</td>)}</tr>)}</tbody></table></div></section>{records.length > 0 && <section className="card recent"><div className="card-head"><div><p className="eyebrow">WORKSPACE RECORDS</p><h3>Connected operational entries</h3></div></div><div className="record-list">{records.map(record => <div className="record-row" key={record.id}><div><b>{record.title}</b><span>{record.details || 'No remarks'}</span></div><em>{record.status}</em></div>)}</div></section>}{adding && <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">CONNECTED MODULE</p><h2>Add {module}</h2></div><button type="button" className="icon-button" onClick={() => setAdding(false)}><X/></button></div><div className="form-grid"><label className="wide">Title<input name="title" required placeholder="Record title"/></label><label>Status<select name="status" defaultValue="OPEN"><option>OPEN</option><option>IN_PROGRESS</option><option>PENDING</option><option>COMPLETED</option><option>APPROVED</option></select></label><label className="wide">Details<textarea name="details" placeholder="Notes, amount, customer or operational context"/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={() => setAdding(false)}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving...' : 'Save record'}</button></div></form></div>}</div>;
}
