import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Bell, Building2, CalendarClock, ChevronDown, CircleDollarSign, ClipboardList, LayoutDashboard, LogOut, Menu, Plus, Search, Users, X } from 'lucide-react';
import { api, Dashboard as DashboardData, Lead, User, Workspace } from './api';

const nav = [{ icon: LayoutDashboard, name: 'Overview' }, { icon: Users, name: 'Leads' }, { icon: Building2, name: 'Inventory' }, { icon: CalendarClock, name: 'Site Visits' }, { icon: CircleDollarSign, name: 'Collections' }, { icon: ClipboardList, name: 'Reports' }];
const navFor = (roles: string[]) => {
  const has = (role: string) => roles.includes(role);
  if (has('CUSTOMER')) return nav.filter(item => ['Overview', 'Collections'].includes(item.name));
  if (has('SUPPORT_EXECUTIVE')) return nav.filter(item => ['Overview', 'Leads'].includes(item.name));
  if (has('HR_MANAGER') || has('HR_EXECUTIVE')) return nav.filter(item => ['Overview', 'Reports'].includes(item.name));
  if (has('PROCUREMENT_MANAGER') || has('LEGAL_OFFICER') || has('AUDITOR')) return nav.filter(item => ['Overview', 'Reports'].includes(item.name));
  if (has('ACCOUNTS_MANAGER') || has('ACCOUNTS_EXECUTIVE')) return nav.filter(item => ['Overview', 'Collections', 'Reports'].includes(item.name));
  if (has('INVENTORY_MANAGER')) return nav.filter(item => ['Overview', 'Inventory', 'Reports'].includes(item.name));
  if (has('RECEPTION')) return nav.filter(item => ['Overview', 'Leads', 'Site Visits'].includes(item.name));
  if (has('TELECALLER')) return nav.filter(item => ['Overview', 'Leads'].includes(item.name));
  return nav;
};
const canCreateLead = (roles: string[]) => roles.some(role => ['SUPER_ADMIN', 'ADMIN', 'SALES_MANAGER', 'SALES_EXECUTIVE', 'TELECALLER', 'RECEPTION'].includes(role));

export function App() {
  const [user, setUser] = useState<User | null>(null); const [active, setActive] = useState('Overview'); const [leads, setLeads] = useState<Lead[]>([]); const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [drawer, setDrawer] = useState(false); const [newLead, setNewLead] = useState(false);
  useEffect(() => { if (localStorage.getItem('sv_access_token')) api.me().then(setUser).catch(() => localStorage.clear()); }, []);
  useEffect(() => { if (user) { api.leads().then(p => setLeads(p.content)).catch(() => setLeads([])); api.dashboard().then(setDashboard).catch(() => setDashboard(null)); } }, [user]);
  const stats = useMemo(() => ({ leads: leads.length, qualified: leads.filter(l => ['QUALIFIED', 'SITE_VISIT_SCHEDULED', 'VISITED', 'NEGOTIATION'].includes(l.status)).length, visits: leads.filter(l => l.status === 'SITE_VISIT_SCHEDULED').length, hot: leads.filter(l => l.temperature === 'HOT').length }), [leads]);
  if (!user) return <Login onLoggedIn={setUser}/>;
  const visibleNav = navFor(user.roles); const canCreate = canCreateLead(user.roles); const roleLabel = user.roles[0]?.replaceAll('_', ' ') ?? 'USER';
  return <div className="shell">
    <aside className={drawer ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">SV</div><div><strong>Sai Vandan</strong><span>REAL ESTATE CRM</span></div><button className="mobile-close" onClick={() => setDrawer(false)}><X size={20}/></button></div><div className="project-chip"><span>{roleLabel}</span><strong>Sai Vandan Complex</strong><ChevronDown size={15}/></div><nav>{visibleNav.map(item => <button className={active === item.name ? 'nav-item active' : 'nav-item'} onClick={() => { setActive(item.name); setDrawer(false); }} key={item.name}><item.icon size={19}/>{item.name}</button>)}</nav><div className="sidebar-bottom"><div className="support">Need assistance?<br/><b>Contact system support</b></div><button className="nav-item" onClick={() => { localStorage.clear(); setUser(null); }}><LogOut size={19}/>Sign out</button></div></aside>
    {drawer && <div className="overlay" onClick={() => setDrawer(false)}/>}
    <main><header><button className="icon-button hamburger" onClick={() => setDrawer(true)}><Menu size={22}/></button><div className="header-title"><p>Friday, 31 July 2026</p><h1>{active === 'Overview' ? `Good morning, ${user.fullName.split(' ')[0]}` : active}</h1></div><div className="header-actions"><label className="search"><Search size={18}/><input placeholder="Search customers, units..."/></label><button className="icon-button notification"><Bell size={19}/><i/></button><div className="avatar">{user.fullName.split(' ').map(s => s[0]).slice(0, 2).join('')}</div></div></header>
    {active === 'Overview' ? <Dashboard dashboard={dashboard} leads={leads} canCreate={canCreate} onLead={() => setNewLead(true)}/> : active === 'Leads' ? <Leads leads={leads} canCreate={canCreate} onLead={() => setNewLead(true)}/> : <WorkspaceView module={active} />} </main>
    {newLead && canCreate && <NewLead onClose={() => setNewLead(false)} onCreated={lead => { setLeads(current => [lead, ...current]); setDashboard(null); api.dashboard().then(setDashboard); setNewLead(false); setActive('Leads'); }}/>} </div>;
}

function Login({ onLoggedIn }: { onLoggedIn: (u: User) => void }) {
  const [email, setEmail] = useState('admin@saivandan.local'); const [password, setPassword] = useState('ChangeMe!2026'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const result = await api.login(email, password); localStorage.setItem('sv_access_token', result.accessToken); localStorage.setItem('sv_refresh_token', result.refreshToken); onLoggedIn(result.user); } catch (err) { setError(err instanceof Error ? err.message : 'Could not sign in.'); } finally { setBusy(false); } };
  return <div className="login-page"><section className="login-panel"><div className="brand"><div className="brand-mark">SV</div><div><strong>Sai Vandan</strong><span>REAL ESTATE CRM</span></div></div><div className="login-copy"><p className="eyebrow">WELCOME BACK</p><h1>Built for every<br/>property moment.</h1><p>One elegant workspace for your sales, inventory, finance and customer teams.</p></div><div className="login-building"/></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><p className="eyebrow">SECURE SIGN IN</p><h2>Welcome to Sai Vandan</h2><p className="muted">Enter your credentials to access your workspace.</p>{error && <p className="error">{error}</p>}<label>Work email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required/></label><button className="primary full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in securely'}</button><p className="help">Local demo account is pre-filled.</p></form></section></div>;
}

function Dashboard({ dashboard, leads, canCreate, onLead }: { dashboard: DashboardData | null; leads: Lead[]; canCreate: boolean; onLead: () => void }) {
  if (!dashboard) return <div className="page coming"><p className="eyebrow">LOADING YOUR WORKSPACE</p><h2>Preparing dashboard...</h2></div>;
  const tones = ['green', 'gold', 'blue', 'coral'];
  return <div className="page"><div className="page-top"><div><p className="eyebrow">{dashboard.subtitle}</p><h2>{dashboard.title}</h2></div>{canCreate && <button className="primary" onClick={onLead}><Plus size={18}/>New enquiry</button>}</div><section className="stat-grid">{dashboard.metrics.map((metric, index) => <Stat key={metric.label} label={metric.label} value={metric.value} change={metric.note} tone={tones[index]}/>)}</section><section className="dashboard-grid"><article className="card performance"><div className="card-head"><div><p className="eyebrow">ROLE WORKSPACE</p><h3>{dashboard.role.replaceAll('_', ' ')}</h3></div><span className="count">LIVE</span></div><div className="bar-chart">{dashboard.metrics.map((metric, index) => <div key={metric.label}><span>{metric.label}</span><i style={{ height: `${38 + index * 13}%` }}/></div>)}</div><div className="chart-legend"><span><i className="dot green"/>Role-specific data</span><strong>{dashboard.modules.length} modules enabled</strong></div></article><article className="card goals"><p className="eyebrow">YOUR ACCESS</p><h3>{dashboard.modules.length} <span>active modules</span></h3><div className="progress"><i style={{ width: `${Math.max(28, dashboard.modules.length * 20)}%` }}/></div><p><b>{dashboard.queue.reduce((total, item) => total + item.count, 0)}</b> actions in your queue</p><button className="text-button">Role controls active <span>-&gt;</span></button></article><article className="card followups"><div className="card-head"><div><p className="eyebrow">ACTION QUEUE</p><h3>Priority work</h3></div><span className="count">{dashboard.queue.reduce((total, item) => total + item.count, 0)}</span></div>{dashboard.queue.map((item, index) => <div className="followup" key={item.label}><div className={`initial ${index === 1 ? 'sand' : ''}`}>{item.count}</div><div><b>{item.label}</b><span>{item.note}</span></div><button>Open</button></div>)}</article></section><section className="card recent"><div className="card-head"><div><p className="eyebrow">RECENT CRM ACTIVITY</p><h3>Lead pipeline</h3></div>{canCreate && <button className="text-button" onClick={onLead}>Add enquiry</button>}</div><LeadTable leads={leads.slice(0, 5)}/></section></div>;
}
function Stat({ label, value, change, tone = 'green' }: { label: string; value: string; change: string; tone?: string }) { return <article className={`stat-card ${tone}`}><p>{label}</p><h3>{value}</h3><span>{change}</span></article>; }
function Leads({ leads, canCreate, onLead }: { leads: Lead[]; canCreate: boolean; onLead: () => void }) { return <div className="page"><div className="page-top"><div><p className="eyebrow">CUSTOMER RELATIONSHIP MANAGEMENT</p><h2>Lead pipeline</h2></div>{canCreate && <button className="primary" onClick={onLead}><Plus size={18}/>New enquiry</button>}</div><section className="card recent"><div className="filters"><button className="filter active">All leads</button><button className="filter">New</button><button className="filter">Qualified</button><button className="filter">Follow-up due</button></div><LeadTable leads={leads}/></section></div>; }
function LeadTable({ leads }: { leads: Lead[] }) { return <div className="table-wrap"><table><thead><tr><th>Lead</th><th>Source</th><th>Status</th><th>Assigned to</th><th>Created</th></tr></thead><tbody>{leads.length ? leads.map(l => <tr key={l.id}><td><b>{l.customerName}</b><small>{l.mobile} - {l.leadNumber}</small></td><td>{l.source}</td><td><span className={`badge ${l.status.toLowerCase()}`}>{l.status.replaceAll('_', ' ')}</span></td><td>{l.assignedTo ?? 'Unassigned'}</td><td>{new Date(l.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</td></tr>) : <tr><td colSpan={5} className="empty">No enquiries yet. Add your first customer lead to begin.</td></tr>}</tbody></table></div>; }
function NewLead({ onClose, onCreated }: { onClose: () => void; onCreated: (l: Lead) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setBusy(true); const f = new FormData(e.currentTarget); try { const lead = await api.createLead({ customerName: f.get('customerName'), mobile: f.get('mobile'), email: f.get('email') || null, city: f.get('city') || null, source: f.get('source'), preferredConfiguration: f.get('configuration') || null, temperature: f.get('temperature'), loanRequired: f.get('loanRequired') === 'on', purchasePurpose: f.get('purchasePurpose') || null, notes: f.get('notes') || null }); onCreated(lead); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save lead.'); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW CUSTOMER</p><h2>Create enquiry</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div>{error && <p className="error">{error}</p>}<div className="form-grid"><label>Customer name<input name="customerName" required placeholder="Full name"/></label><label>Mobile number<input name="mobile" required placeholder="10-digit mobile number"/></label><label>Email<input name="email" type="email" placeholder="name@email.com"/></label><label>City<input name="city" placeholder="City"/></label><label>Lead source<select name="source" defaultValue="Website"><option>Website</option><option>Walk-in</option><option>Referral</option><option>WhatsApp</option><option>Facebook / Instagram</option><option>Google Ads</option><option>Phone Call</option><option>Property Portal</option></select></label><label>Configuration<select name="configuration"><option value="">Not decided</option><option>1 BHK</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option></select></label><label>Priority<select name="temperature" defaultValue="WARM"><option value="HOT">Hot</option><option value="WARM">Warm</option><option value="COLD">Cold</option></select></label><label className="check"><input type="checkbox" name="loanRequired"/> Loan assistance required</label><label className="wide">Notes<textarea name="notes" placeholder="Requirement, budget, preferred location..."/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving...' : 'Create enquiry'}</button></div></form></div>;
}
function WorkspaceView({ module }: { module: string }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [error, setError] = useState('');
  const key = ({ Inventory: 'inventory', 'Site Visits': 'site-visits', Collections: 'collections', Reports: 'reports' } as Record<string, string>)[module] ?? module.toLowerCase();
  useEffect(() => { setWorkspace(null); setError(''); api.workspace(key).then(setWorkspace).catch(err => setError(err instanceof Error ? err.message : 'Unable to load this workspace.')); }, [key]);
  if (error) return <div className="page coming"><p className="eyebrow">ROLE RESTRICTION</p><h2>Access unavailable</h2><p>{error}</p></div>;
  if (!workspace) return <div className="page coming"><p className="eyebrow">LOADING MODULE</p><h2>Preparing {module}...</h2></div>;
  const columns = workspace.rows.length ? Object.keys(workspace.rows[0]) : [];
  return <div className="page"><div className="page-top"><div><p className="eyebrow">{workspace.role.replaceAll('_', ' ')} WORKSPACE</p><h2>{workspace.title}</h2></div></div><section className="card recent"><div className="card-head"><div><p className="eyebrow">LIVE DATA</p><h3>{workspace.rows.length} records available</h3></div><span className="count">CONNECTED</span></div><div className="table-wrap"><table><thead><tr>{columns.map(column => <th key={column}>{column.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{workspace.rows.map((row, index) => <tr key={index}>{columns.map(column => <td key={column}>{String(row[column] ?? '-').replaceAll('_', ' ')}</td>)}</tr>)}</tbody></table></div></section></div>;
}
