package com.saivandan.crm.user;

public enum RoleCode {
  SUPER_ADMIN, ADMIN, MANAGEMENT, SALES_MANAGER, SALES_EXECUTIVE, TELECALLER, RECEPTION,
  INVENTORY_MANAGER, ACCOUNTS_MANAGER, ACCOUNTS_EXECUTIVE, HR_MANAGER, HR_EXECUTIVE,
  PROCUREMENT_MANAGER, LEGAL_OFFICER, SUPPORT_EXECUTIVE, AUDITOR, CUSTOMER
}

