ALTER TABLE leads ADD COLUMN IF NOT EXISTS qualification_score INT DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS duplicate_of UUID REFERENCES leads(id);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS consent BOOLEAN DEFAULT TRUE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS communication_preference VARCHAR(30);
ALTER TABLE lead_activities ADD COLUMN IF NOT EXISTS call_duration_seconds INT;
ALTER TABLE lead_activities ADD COLUMN IF NOT EXISTS customer_response VARCHAR(500);
CREATE TABLE lead_assignment_history (id UUID DEFAULT RANDOM_UUID() PRIMARY KEY, lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE, from_user_id UUID REFERENCES users(id), to_user_id UUID REFERENCES users(id), reason VARCHAR(500), changed_by UUID REFERENCES users(id), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE negotiations (id UUID DEFAULT RANDOM_UUID() PRIMARY KEY, lead_id UUID NOT NULL REFERENCES leads(id), unit_id UUID REFERENCES units(id), offered_price DECIMAL(15,2) NOT NULL, discount_amount DECIMAL(15,2) DEFAULT 0, special_offer VARCHAR(500), competitor VARCHAR(160), status VARCHAR(30) NOT NULL DEFAULT 'PENDING', requested_by UUID REFERENCES users(id), approved_by UUID REFERENCES users(id), approval_comment VARCHAR(1000), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE quotation_versions (id UUID DEFAULT RANDOM_UUID() PRIMARY KEY, lead_id UUID NOT NULL REFERENCES leads(id), unit_id UUID REFERENCES units(id), version_no INT NOT NULL, base_price DECIMAL(15,2) NOT NULL, floor_rise DECIMAL(15,2) DEFAULT 0, parking_amount DECIMAL(15,2) DEFAULT 0, gst_amount DECIMAL(15,2) DEFAULT 0, registration_estimate DECIMAL(15,2) DEFAULT 0, discount_amount DECIMAL(15,2) DEFAULT 0, special_offer VARCHAR(500), total_amount DECIMAL(15,2) NOT NULL, expires_at DATE, status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', created_by UUID REFERENCES users(id), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(lead_id,version_no));
ALTER TABLE site_visits ADD COLUMN IF NOT EXISTS pickup_address VARCHAR(500);
ALTER TABLE site_visits ADD COLUMN IF NOT EXISTS visitor_count INT DEFAULT 1;
ALTER TABLE site_visits ADD COLUMN IF NOT EXISTS preferred_unit_id UUID REFERENCES units(id);
ALTER TABLE site_visits ADD COLUMN IF NOT EXISTS rating INT;
ALTER TABLE site_visits ADD COLUMN IF NOT EXISTS objections VARCHAR(1000);
ALTER TABLE site_visits ADD COLUMN IF NOT EXISTS next_action VARCHAR(500);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS quotation_id UUID REFERENCES quotation_versions(id);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirmed_by UUID REFERENCES users(id);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS payment_validated BOOLEAN DEFAULT FALSE;
CREATE INDEX idx_negotiations_lead_status ON negotiations(lead_id,status);
CREATE INDEX idx_quotations_lead_version ON quotation_versions(lead_id,version_no);
CREATE INDEX idx_site_visits_date_status ON site_visits(visit_date,status);
